# Generated by Django 3.0.5 on 2020-05-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeolocationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname', models.CharField(max_length=255)),
                ('latdegree', models.IntegerField(blank=True, null=True)),
                ('latminute', models.IntegerField(blank=True, null=True)),
                ('latsecond', models.FloatField(blank=True, null=True)),
                ('longdegree', models.IntegerField(blank=True, null=True)),
                ('longminute', models.IntegerField(blank=True, null=True)),
                ('longsecond', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'geolocationdatas',
                'db_table': 'geolocationdata',
            },
        ),
        migrations.CreateModel(
            name='GeolocationInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geodescription', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'geodescriptions',
                'db_table': 'geodescription',
            },
        ),
    ]
