# Generated by Django 3.0.5 on 2020-05-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocationdata',
            name='latdirection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geolocationdata',
            name='longdirection',
            field=models.TextField(blank=True, null=True),
        ),
    ]
